package servlet;

import domain.User;
import service.UserService;
import service.impl.UserServiceImpl;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import java.io.IOException;

@WebServlet("/loginServlet")
public class LoginServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        this.doPost(req, resp);
    }

    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {

        req.setCharacterEncoding("UTF-8");
//        get params from jsp
        String name = req.getParameter("name");
        String password = req.getParameter("password");
        String verifycode = req.getParameter("verifycode");
//      get code generated by codeServlet
        HttpSession session = req.getSession();
        String checkcodeServer = (String) session.getAttribute("CHECKCODE_SERVER");
//        remove the session, in case of code reused.
        session.removeAttribute("CHECKCODE_SERVER");

        System.out.println(checkcodeServer);
        System.out.println(verifycode);
        System.out.println(name);
        System.out.println(password);

//        if code is correct verify the username and password
        if (checkcodeServer != null && checkcodeServer.equalsIgnoreCase(verifycode)){
            UserService userService = new UserServiceImpl();
//            find user by username and password
            User user = userService.login(name, password);
            if (user != null){
//                login success
                session.setAttribute("user", user);
                resp.sendRedirect(req.getContextPath() + "/index.jsp");
            }else{
//                didn't find this user in DB.
                req.setAttribute("login_msg","username or password incorrect.");
                req.getRequestDispatcher("/login.jsp").forward(req, resp);
            }
        }else{
//            check code error
            req.setAttribute("login_msg","check code error.");
            req.getRequestDispatcher("/login.jsp").forward(req, resp);
        }
    }
}
